name: smena

services:
  update-server:
    container_name: smena-update-server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5100"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - smena_edge
    restart: unless-stopped

networks:
  smena_edge:
    external: true
    driver: bridge
